[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"
authors = ["Jan Jitse <janjitse@gmail.com>"]

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
fxhash = "0.2.1"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"

[profile.release]
strip = "debuginfo"
